[package]
name = "host_client"
version = "0.1.0"
edition = "2021"

[dependencies]
schema = { path = "../schema" }
postcard = "1.0.10"
postcard-rpc = {version="0.7.0", features = ["use-std","raw-nusb"]}
tokio = {version="1.40.0",features = ["rt-multi-thread","macros","time",]}

