name: kaggle-env

channels:
  - conda-forge

dependencies:
  - kaggle
  - pip
  - python
  - pandas
  - numpy
  - matplotlib
  - scikit-learn
  - jupyter
  - seaborn
  - tensorflow
  - keras
  - pytorch
  - torchvision
  - opencv
  - tqdm
  - pillow
  - tensorboard
  