name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  rust-build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build all
      run: sh -x ./scripts/cargo_build_all.sh

  rust-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Test all
      run: sh -x ./scripts/cargo_test_all.sh

  rust-clippy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: clippy all
      run: sh -x ./scripts/cargo_clippy_all.sh